name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # As actions/cache@v2 saves files only once per each key,
      # we use different keys (by github.run_id) for each job,
      # though retrieving old cache via restore-keys.
      # https://github.com/actions/cache/issues/342#issuecomment-673371329
      - name: Cache Isabelle heaps
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-Isabelle2020-${{ hashFiles('ROOT') }}-${{ github.run_id }}
          path: .heaps
          restore-keys: |
            ${{ runner.os }}-Isabelle2020

      - name: Build documents
        uses: NieDzejkob/isabelle-action@v1.4
        with:
          args: "build -D . -v"
          heapCacheDir: .heaps

      - name: Prepare deploy
        run: python3 deploy.py

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: built-pdfs
          FOLDER: output
          CLEAN: true
